In [63]:
pip install kaggle

Requirement already satisfied: kaggle in c:\users\nivedha\anaconda3\lib\site-packages (1.6.17)
Requirement already satisfied: six>=1.10 in c:\users\nivedha\appdata\roaming\python\python312\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\nivedha\anaconda3\lib\site-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in c:\users\nivedha\appdata\roaming\python\python312\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\nivedha\anaconda3\lib\site-packages (from kaggle) (2.32.2)
Requirement already satisfied: tqdm in c:\users\nivedha\anaconda3\lib\site-packages (from kaggle) (4.66.4)
Requirement already satisfied: python-slugify in c:\users\nivedha\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\nivedha\anaconda3\lib\site-packages (from kaggle) (2.2.2)
Requirement already satisfied: bleach in c:\users\nivedha\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\nivedha\appdata\roaming\python\python312\site-packages (from bleach->kaggle) (24.2)
Requirement already satisfied: webencodings in c:\users\nivedha\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\nivedha\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\nivedha\anaconda3\lib\site-packages (from requests->kaggle) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\nivedha\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: colorama in c:\users\nivedha\appdata\roaming\python\python312\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [64]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
orders.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [65]:
import zipfile
import pandas as pd
df = pd.read_csv("orders.csv.zip")
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [66]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', 'unknown',
       'First Class', nan, 'Same Day'], dtype=object)

In [73]:
df=pd.read_csv('orders.csv.zip',na_values=['Not available','unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', 'Not Available', nan,
       'First Class', 'Same Day'], dtype=object)

In [75]:
df.rename(columns={'Order Id':'order_id', 'City':'city'})

,order_id,Order Date,Ship Mode,Segment,Country,city,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [77]:
df.dtypes

Order Id             int64
Order Date          object
Ship Mode           object
Segment             object
Country             object
City                object
State               object
Postal Code          int64
Region              object
Category            object
Sub Category        object
Product Id          object
cost price           int64
List Price           int64
Quantity             int64
Discount Percent     int64
dtype: object

In [79]:
df.columns=df.columns.str.replace(' ','_')

In [81]:
df.dtypes

Order_Id             int64
Order_Date          object
Ship_Mode           object
Segment             object
Country             object
City                object
State               object
Postal_Code          int64
Region              object
Category            object
Sub_Category        object
Product_Id          object
cost_price           int64
List_Price           int64
Quantity             int64
Discount_Percent     int64
dtype: object

In [83]:
df['discount']=df['List_Price']*df['Discount_Percent']*.01

In [85]:
df['sales_Price']=df['List_Price']-df['discount']

In [89]:
df['profit']=df['sales_Price']-df['cost_price']

In [91]:
df

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount,sales_Price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [93]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])

In [95]:
df.dtypes

Order_Id                     int64
Order_Date          datetime64[ns]
Ship_Mode                   object
Segment                     object
Country                     object
City                        object
State                       object
Postal_Code                  int64
Region                      object
Category                    object
Sub_Category                object
Product_Id                  object
cost_price                   int64
List_Price                   int64
Quantity                     int64
Discount_Percent             int64
discount                   float64
sales_Price                float64
profit                     float64
dtype: object

In [35]:
df1=df.iloc[:,:10]

In [37]:
df2=df.iloc[:,10:]

In [226]:
df1.dtypes

Order_Id                int64
Order_Date     datetime64[ns]
Ship_Mode              object
Segment                object
Country                object
City                   object
State                  object
Postal_Code             int64
Region                 object
Category               object
dtype: object

In [97]:
df['Ship_Mode']=df['Ship_Mode'].str.rstrip()

In [99]:
df['Segment']=df['Segment'].str.rstrip()

In [101]:
df['Country']=df['Country'].str.rstrip()

In [103]:
df['City']=df['City'].str.rstrip()

In [105]:
df['State']=df['State'].str.rstrip()

In [107]:
df['Region']=df['Region'].str.rstrip()

In [109]:
df['Category']=df['Category'].str.rstrip()

In [111]:
df

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount,sales_Price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [113]:
order=df

In [115]:
order

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount,sales_Price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [39]:
df2

,Sub_Category,Product_Id,cost_price,List_Price,Quantity,Discount_Percent,discount,sales_Price,profit
0,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...
9989,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9990,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9991,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9992,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9993,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [117]:
db_config ={
    'host':'localhost',
     'user':'root',
      'password':'kasthuri67' 
}

In [174]:
df1

,Order_Id,Order_Date,Ship_Mode,Segment,Country,City,State,Postal_Code,Region,Category
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies
...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies

In [260]:
df1.dtypes

Order_Id                int64
Order_Date     datetime64[ns]
Ship_Mode              object
Segment                object
Country                object
City                   object
State                  object
Postal_Code             int64
Region                 object
Category               object
dtype: object

In [119]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\nivedha\anaconda3\lib\site-packages (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [124]:
conn = pymysql.connect(**db_config)
cursor=conn.cursor()

In [126]:
cursor.execute("create database if not exists retail_orders")

1

In [122]:
import pymysql

In [128]:
cursor.execute("use retail_orders")

0

cursor.execute("Create table if not exists df_orders( Order_Id int,Order_Date date,Ship_Mode varchar(20),Segment varchar(20),Country varchar(20),City varchar(20),State varchar(20),Postal_Code int,Region varchar(20),Category varchar(20)"))

In [132]:
cursor.execute("create table if not exists order_guvi( Order_Id int,Order_Date date,Ship_Mode varchar(20),Segment varchar(20),Country varchar(20),City varchar(20),State varchar(20),Postal_Code int,Region varchar(20),Category varchar(20),Sub_Category varchar(20),Product_Id text,	cost_price int,	List_Price int,	Quantity int,	Discount_Percent int,	discount int,	sales_Price int,	profit int)"),

(0,)

In [136]:
insert_query="""INSERT INTO order_guvi(Order_Id ,Order_Date ,Ship_Mode,Segment,Country ,City ,State,Postal_Code,Region ,Category ,Sub_Category,Product_Id ,	cost_price ,	List_Price,	Quantity ,	Discount_Percent,	discount ,	sales_Price ,	profit)values(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"""

In [158]:

for index, row in df.iterrows():
    cursor.execute(insert_query,(row["Order_Id"] ,row["Order_Date"],row["Ship_Mode"],row["Segment"],row["Country"] ,row["City"],row["State"],row["Postal_Code"],row["Region"] ,row["Category"],
        row["Sub_Category"], row["Product_Id"], row["cost_price"], row["List_Price"],
        row["Quantity"], row["Discount_Percent"], row["discount"], row["sales_Price"],
        row["profit"]))

In [159]:
conn.commit()

In [156]:
df=df.where(pd.notnull(df),None)

In [274]:
import mysql.connector